const COUNTRIES = [
  { name: "Afghanistan", continent: "Asia" },
  { name: "Albania", continent: "Europe" },
  { name: "Algeria", continent: "Africa" },
  { name: "Andorra", continent: "Europe" },
  { name: "Angola", continent: "Africa" },
  { name: "Argentina", continent: "South America" },
  { name: "Armenia", continent: "Asia" },
  { name: "Australia", continent: "Oceania" },
  { name: "Austria", continent: "Europe" },
  { name: "Azerbaijan", continent: "Asia" },
  { name: "Bahrain", continent: "Asia" },
  { name: "Bangladesh", continent: "Asia" },
  { name: "Belarus", continent: "Europe" },
  { name: "Belgium", continent: "Europe" },
  { name: "Belize", continent: "North America" },
  { name: "Benin", continent: "Africa" },
  { name: "Bhutan", continent: "Asia" },
  { name: "Bolivia", continent: "South America" },
  { name: "Bosnia and Herzegovina", continent: "Europe" },
  { name: "Botswana", continent: "Africa" },
  { name: "Brazil", continent: "South America" },
  { name: "Bulgaria", continent: "Europe" },
  { name: "Burkina Faso", continent: "Africa" },
  { name: "Burundi", continent: "Africa" },
  { name: "Cambodia", continent: "Asia" },
  { name: "Cameroon", continent: "Africa" },
  { name: "Canada", continent: "North America" },
  { name: "Chad", continent: "Africa" },
  { name: "Chile", continent: "South America" },
  { name: "China", continent: "Asia" },
  { name: "Colombia", continent: "South America" },
  { name: "Costa Rica", continent: "North America" },
  { name: "Croatia", continent: "Europe" },
  { name: "Cuba", continent: "North America" },
  { name: "Cyprus", continent: "Europe" },
  { name: "Czechia", continent: "Europe" },
  { name: "Democratic Republic of the Congo", continent: "Africa" },
  { name: "Denmark", continent: "Europe" },
  { name: "Dominican Republic", continent: "North America" },
  { name: "Ecuador", continent: "South America" },
  { name: "Egypt", continent: "Africa" },
  { name: "El Salvador", continent: "North America" },
  { name: "Estonia", continent: "Europe" },
  { name: "Ethiopia", continent: "Africa" },
  { name: "Finland", continent: "Europe" },
  { name: "France", continent: "Europe" },
  { name: "Gabon", continent: "Africa" },
  { name: "Georgia", continent: "Asia" },
  { name: "Germany", continent: "Europe" },
  { name: "Ghana", continent: "Africa" },
  { name: "Greece", continent: "Europe" },
  { name: "Guatemala", continent: "North America" },
  { name: "Guinea", continent: "Africa" },
  { name: "Haiti", continent: "North America" },
  { name: "Honduras", continent: "North America" },
  { name: "Hungary", continent: "Europe" },
  { name: "Iceland", continent: "Europe" },
  { name: "India", continent: "Asia" },
  { name: "Indonesia", continent: "Asia" },
  { name: "Iran", continent: "Asia" },
  { name: "Iraq", continent: "Asia" },
  { name: "Ireland", continent: "Europe" },
  { name: "Israel", continent: "Asia" },
  { name: "Ivory Coast", continent: "Africa" },
  { name: "Italy", continent: "Europe" },
  { name: "Jamaica", continent: "North America" },
  { name: "Japan", continent: "Asia" },
  { name: "Jordan", continent: "Asia" },
  { name: "Kazakhstan", continent: "Asia" },
  { name: "Kenya", continent: "Africa" },
  { name: "Kuwait", continent: "Asia" },
  { name: "Kyrgyzstan", continent: "Asia" },
  { name: "Laos", continent: "Asia" },
  { name: "Latvia", continent: "Europe" },
  { name: "Lebanon", continent: "Asia" },
  { name: "Liberia", continent: "Africa" },
  { name: "Libya", continent: "Africa" },
  { name: "Lithuania", continent: "Europe" },
  { name: "Luxembourg", continent: "Europe" },
  { name: "Madagascar", continent: "Africa" },
  { name: "Malawi", continent: "Africa" },
  { name: "Malaysia", continent: "Asia" },
  { name: "Mali", continent: "Africa" },
  { name: "Mexico", continent: "North America" },
  { name: "Moldova", continent: "Europe" },
  { name: "Mongolia", continent: "Asia" },
  { name: "Montenegro", continent: "Europe" },
  { name: "Morocco", continent: "Africa" },
  { name: "Mozambique", continent: "Africa" },
  { name: "Myanmar", continent: "Asia" },
  { name: "Namibia", continent: "Africa" },
  { name: "Nepal", continent: "Asia" },
  { name: "Netherlands", continent: "Europe" },
  { name: "New Zealand", continent: "Oceania" },
  { name: "Nicaragua", continent: "North America" },
  { name: "Niger", continent: "Africa" },
  { name: "Nigeria", continent: "Africa" },
  { name: "North Korea", continent: "Asia" },
  { name: "North Macedonia", continent: "Europe" },
  { name: "Norway", continent: "Europe" },
  { name: "Oman", continent: "Asia" },
  { name: "Pakistan", continent: "Asia" },
  { name: "Panama", continent: "North America" },
  { name: "Paraguay", continent: "South America" },
  { name: "Peru", continent: "South America" },
  { name: "Philippines", continent: "Asia" },
  { name: "Poland", continent: "Europe" },
  { name: "Portugal", continent: "Europe" },
  { name: "Qatar", continent: "Asia" },
  { name: "Republic of the Congo", continent: "Africa" },
  { name: "Romania", continent: "Europe" },
  { name: "Russia", continent: "Europe" },
  { name: "Rwanda", continent: "Africa" },
  { name: "Saudi Arabia", continent: "Asia" },
  { name: "Senegal", continent: "Africa" },
  { name: "Serbia", continent: "Europe" },
  { name: "Singapore", continent: "Asia" },
  { name: "Slovakia", continent: "Europe" },
  { name: "Slovenia", continent: "Europe" },
  { name: "Somalia", continent: "Africa" },
  { name: "South Africa", continent: "Africa" },
  { name: "South Korea", continent: "Asia" },
  { name: "Spain", continent: "Europe" },
  { name: "Sri Lanka", continent: "Asia" },
  { name: "Sudan", continent: "Africa" },
  { name: "Sweden", continent: "Europe" },
  { name: "Switzerland", continent: "Europe" },
  { name: "Syria", continent: "Asia" },
  { name: "Taiwan", continent: "Asia" },
  { name: "Tajikistan", continent: "Asia" },
  { name: "Tanzania", continent: "Africa" },
  { name: "Thailand", continent: "Asia" },
  { name: "Tunisia", continent: "Africa" },
  { name: "Turkey", continent: "Asia" },
  { name: "Uganda", continent: "Africa" },
  { name: "Ukraine", continent: "Europe" },
  { name: "United Arab Emirates", continent: "Asia" },
  { name: "United Kingdom", continent: "Europe" },
  { name: "United States", continent: "North America" },
  { name: "Uruguay", continent: "South America" },
  { name: "Uzbekistan", continent: "Asia" },
  { name: "Venezuela", continent: "South America" },
  { name: "Vietnam", continent: "Asia" },
  { name: "Yemen", continent: "Asia" },
  { name: "Zambia", continent: "Africa" },
  { name: "Zimbabwe", continent: "Africa" },
];
